-- =====================================================
-- Selective Database Cleanup Script for sp_QuoteCalc
-- Preserves seed data from database_setup.sql
-- Removes only test-specific data generated by sp_QuoteCalc
-- Generated: October 21, 2025
-- =====================================================
--
-- Seed Data Analysis from database_setup.sql:
-- - VehicleMakes: IDs 1-8 (Ford, Toyota, Chevrolet, Honda, Nissan, BMW, Mercedes-Benz, Volkswagen) - PRESERVE
-- - VehicleModels: IDs 1-15 (Various models) - PRESERVE
-- - Departments: IDs 1-8 (Sales, Marketing, Operations, IT, HR, Finance, Maintenance, Security) - PRESERVE
-- - Locations: IDs 1-8 (Seattle HQ through Training Center) - PRESERVE
-- - Drivers: IDs 1-5 (Standard test driver set) - PRESERVE
-- - Vehicles: IDs 1-5 (Standard test fleet) - PRESERVE
--
-- Test Data Ranges (generated by sp_QuoteCalc):
-- - VehicleQuotes: All records (no seed data exists)
-- - QuoteLineItems: All records (no seed data exists)
-- - QuoteFollowUps: All records (no seed data exists)
--
-- Strategy: Remove ALL test data from VehicleQuotes and related tables
-- (sp_QuoteCalc creates all new data, no seed data to preserve)
-- =====================================================

USE FleetManagement;
GO

-- Disable foreign key constraints temporarily
-- Using explicit approach instead of sp_MSforeachtable for compatibility
DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql += 'ALTER TABLE ' + QUOTENAME(SCHEMA_NAME(schema_id)) + '.' + QUOTENAME(name) + ' NOCHECK CONSTRAINT ALL;' + CHAR(13) + CHAR(10)
FROM sys.tables;
EXEC sp_executesql @sql;

-- =====================================================
-- REMOVE TEST DATA ONLY (preserve seed data)
-- Delete in correct order: child tables before parent tables
-- =====================================================

-- Remove all quote-related data (no seed data exists in these tables)
DELETE FROM QuoteFollowUps;
DELETE FROM QuoteLineItems;
DELETE FROM VehicleQuotes;

-- DO NOT delete from VehicleMakes (seed data: IDs 1-8)
-- DO NOT delete from VehicleModels (seed data: IDs 1-15)
-- DO NOT delete from Departments (seed data: IDs 1-8)
-- DO NOT delete from Locations (seed data: IDs 1-8)
-- DO NOT delete from Drivers (seed data: IDs 1-5)
-- DO NOT delete from Vehicles (seed data: IDs 1-5)

-- =====================================================
-- RESET IDENTITY COLUMNS TO START VALUES
-- =====================================================

-- Reset quote-related tables to start from 1 (no seed data to preserve)
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID('VehicleQuotes'))
    DBCC CHECKIDENT ('VehicleQuotes', RESEED, 0);  -- Next insert: 1

IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID('QuoteLineItems'))
    DBCC CHECKIDENT ('QuoteLineItems', RESEED, 0);  -- Next insert: 1

IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id = OBJECT_ID('QuoteFollowUps'))
    DBCC CHECKIDENT ('QuoteFollowUps', RESEED, 0);  -- Next insert: 1

-- =====================================================
-- RE-ENABLE CONSTRAINTS
-- =====================================================
-- Using explicit approach instead of sp_MSforeachtable for compatibility
DECLARE @sql2 NVARCHAR(MAX) = '';
SELECT @sql2 += 'ALTER TABLE ' + QUOTENAME(SCHEMA_NAME(schema_id)) + '.' + QUOTENAME(name) + ' WITH CHECK CHECK CONSTRAINT ALL;' + CHAR(13) + CHAR(10)
FROM sys.tables;
EXEC sp_executesql @sql2;

-- =====================================================
-- VERIFICATION
-- =====================================================

-- Verify seed data still exists (critical lookup/reference data)
IF NOT EXISTS (SELECT 1 FROM VehicleMakes WHERE MakeID BETWEEN 1 AND 8)
    RAISERROR ('CLEANUP ERROR: Seed data missing from VehicleMakes', 16, 1);

IF NOT EXISTS (SELECT 1 FROM VehicleModels WHERE ModelID BETWEEN 1 AND 15)
    RAISERROR ('CLEANUP ERROR: Seed data missing from VehicleModels', 16, 1);

IF NOT EXISTS (SELECT 1 FROM Departments WHERE DepartmentID BETWEEN 1 AND 8)
    RAISERROR ('CLEANUP ERROR: Seed data missing from Departments', 16, 1);

IF NOT EXISTS (SELECT 1 FROM Locations WHERE LocationID BETWEEN 1 AND 8)
    RAISERROR ('CLEANUP ERROR: Seed data missing from Locations', 16, 1);

IF NOT EXISTS (SELECT 1 FROM Drivers WHERE DriverID BETWEEN 1 AND 5)
    RAISERROR ('CLEANUP ERROR: Seed data missing from Drivers', 16, 1);

IF NOT EXISTS (SELECT 1 FROM Vehicles WHERE VehicleID BETWEEN 1 AND 5)
    RAISERROR ('CLEANUP ERROR: Seed data missing from Vehicles', 16, 1);

-- Verify test data removed (quote-related tables should be empty)
IF EXISTS (SELECT 1 FROM VehicleQuotes)
    RAISERROR ('CLEANUP ERROR: VehicleQuotes still contains test data', 16, 1);

IF EXISTS (SELECT 1 FROM QuoteLineItems)
    RAISERROR ('CLEANUP ERROR: QuoteLineItems still contains test data', 16, 1);

IF EXISTS (SELECT 1 FROM QuoteFollowUps)
    RAISERROR ('CLEANUP ERROR: QuoteFollowUps still contains test data', 16, 1);

-- Display cleanup summary
SELECT 
    (SELECT COUNT(*) FROM VehicleMakes) AS VehicleMakes_Count,
    (SELECT COUNT(*) FROM VehicleModels) AS VehicleModels_Count,
    (SELECT COUNT(*) FROM Departments) AS Departments_Count,
    (SELECT COUNT(*) FROM Locations) AS Locations_Count,
    (SELECT COUNT(*) FROM Drivers) AS Drivers_Count,
    (SELECT COUNT(*) FROM Vehicles) AS Vehicles_Count,
    (SELECT COUNT(*) FROM VehicleQuotes) AS VehicleQuotes_Count,
    (SELECT COUNT(*) FROM QuoteLineItems) AS QuoteLineItems_Count,
    (SELECT COUNT(*) FROM QuoteFollowUps) AS QuoteFollowUps_Count;

PRINT 'Database cleanup completed successfully';
PRINT 'Seed data preserved: VehicleMakes (8), VehicleModels (15), Departments (8), Locations (8), Drivers (5), Vehicles (5)';
PRINT 'Test data removed: VehicleQuotes, QuoteLineItems, QuoteFollowUps (all cleared)';